version: '3'

services:
  springapi:
    image: openjdk:10-jre-slim
    container_name: springapi
    ports:
      - 9898:9898
    volumes:
      - ./target/Test-Tienda-0.0.1-SNAPSHOT.jar:/application.jar
    command: ["java", "-jar", "application.jar"]
    networks:
      - backendNetwork
      - frontendNetwork
      
  angular:
    image: nginx:alpine
    container_name: angular
    ports: 
      - 4200:4200
    depends_on:
      - springapi
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./Angular/dist/Tienda-app:/usr/share/nginx/html
    networks:
      - frontendNetwork
    

volumes:
  dockerAngularSpringDatabaseData:
  
networks:
  backendNetwork:
  frontendNetwork:
